### ISSUE TITLE
Unable to create 'PyZ3950_parsetab.py'

### ISSUE THREAD

**Issue by chrism80026** [GSA/ckanext-geodatagov#103]
I've installed the latest version of ckanext-geodatagov as of 10/25/2016 with "pip install -e git+https://github.com/GSA/ckanext-geodatagov#egg=ckanext-geodatagov". This is running as part of CKAN 2.3.4. I'm getting this error:

[:error] [pid 1532] Unable to create 'PyZ3950_parsetab.py'
[:error] [pid 1532] [Errno 13] Permission denied: 'PyZ3950_parsetab.py'

I also have an older version of  running  of ckanext-geodatagov (v1.1-alpha) running with CKAN 2.1aand it's been reporting this error for years without noticeable issues. This was installed before I took over maintaining  CKAN.

I've tried everything I can think of to get this error to go away. It doesn't seem to be a permission or ownership problem at least within the ckanext-geodatagov directory structure and I've disabled SELinux. Where is ckanext-geodatagov trying to create this file? What issues will this cause if it's not fixed?

**Comment by theresaanna** [comment]
Can this be reproduced?
