### ISSUE TITLE
Onlink mandatory for FGDC records?

### ISSUE THREAD

**Issue by torrin47** [GSA/ckanext-geodatagov#92]
We've finally been able to start testing harvests of native geospatial records, and are finding that FGDC records that have no onlink parameter fail the harvest with an error message of "No resources invalid metadata".  Since online linkage is a mandatory-if-applicable field, is there a reason this particular rule is being enforced?  Could it possibly be relaxed?

**Comment by torrin47** [comment]
We've confirmed that the same requirement exists for ISO records - records without a MD_DigitalTransferOptions linkage element are rejected as invalid. We appreciate that online linkages are at the core of what Project Open Data is all about, but object to inconsistent validation standards.

BTW, does this issue belong in a different repo?

**Comment by amilan17** [comment]
@torrin47 - maybe log the issue here instead? 

https://github.com/GSA/data.gov/issues

**Comment by jacimize** [comment]
Torrin already did from what I can see:
https://github.com/GSA/ckanext-geodatagov/issues/92

On Tue, Jan 27, 2015 at 10:52 AM, Anna Milan <notifications@github.com>
wrote:

> @torrin47 <https://github.com/torrin47> - maybe log the issue here
> instead?
>
> https://github.com/GSA/data.gov/issues
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GSA/ckanext-geodatagov/issues/92#issuecomment-71682545>
> .
>



-- 
Jacqueline Mize
Metadata Specialist
Radiance Technologies, Inc.
DOC/NOAA/NESDIS/NODC/NCDDC
1021 Balch Blvd, Suite 1003
Stennis Space Center, MS 39529
email: Jacqueline.Mize@noaa.gov
ph: 228.688.2174

**Comment by torrin47** [comment]
Thanks, moved it over here:
https://github.com/GSA/data.gov/issues/559
Hopefully will get a the wheels turning.
